// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	AlbumID          string      `json:"album_id"`
	AlbumName        string      `json:"album_name"`
	ArtistID         string      `json:"artist_id"`
	CoverUrl         string      `json:"cover_url"`
	AlbumReleaseDate pgtype.Date `json:"album_release_date"`
}

type Artist struct {
	ArtistID   string `json:"artist_id"`
	ArtistName string `json:"artist_name"`
}

type Play struct {
	PlayID    pgtype.UUID      `json:"play_id"`
	TrackID   string           `json:"track_id"`
	PlayedAt  pgtype.Timestamp `json:"played_at"`
	SkippedAt pgtype.Int4      `json:"skipped_at"`
}

type Playlist struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	ImageUrl    string           `json:"image_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type PlaylistTrack struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	TrackID    string      `json:"track_id"`
}

type Track struct {
	TrackID          string      `json:"track_id"`
	TrackName        string      `json:"track_name"`
	Duration         int32       `json:"duration"`
	Popularity       int32       `json:"popularity"`
	AlbumID          string      `json:"album_id"`
	ArtistID         string      `json:"artist_id"`
	Artists          []string    `json:"artists"`
	TrackReleaseDate pgtype.Date `json:"track_release_date"`
}
