// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	AlbumID          string
	AlbumName        string
	ArtistID         string
	CoverUrl         string
	AlbumReleaseDate pgtype.Date
}

type Artist struct {
	ArtistID   string
	ArtistName string
}

type Play struct {
	TrackID   string
	PlayedAt  pgtype.Timestamp
	SkippedAt pgtype.Int4
}

type Playlist struct {
	ID          pgtype.UUID
	Name        string
	Description string
	ImageUrl    string
	CreatedAt   pgtype.Timestamp
}

type PlaylistTrack struct {
	PlaylistID pgtype.UUID
	TrackID    string
}

type Track struct {
	TrackID          string
	TrackName        string
	Duration         int32
	Popularity       int32
	AlbumID          string
	ArtistID         string
	Artists          []string
	TrackReleaseDate pgtype.Date
}
